version: "3"

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: admin_01
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample_db_01
    volumes:
      - "example.env.data:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    tty: true
volumes:
  example.env.data:
networks:
  default:
    external:
      name: example-env-network
