version: "3"

services:
  csharp:
    build: ./csharp/general
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin_01
      DB_PASSWORD: password
      DB_NAME: sample_db_02
    tty: true
    volumes:
      - "example.csharp.general:/root"
  golang:
    build: ./golang/general
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin_01
      DB_PASSWORD: password
      DB_NAME: sample_db_02
    tty: true
    volumes:
      - "example.golang.general:/root"
      - "example.golang.general.go1.14:/go"
  ruby:
    build: ./ruby/general
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin_01
      DB_PASSWORD: password
      DB_NAME: sample_db_02
    volumes:
      - "example.ruby.general:/root"
    tty: true
volumes:
  example.csharp.general:
  example.golang.general:
  example.golang.general.go1.14:
  example.ruby.general:
networks:
  default:
    external:
      name: example-env-network
